/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project4;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



/**
 *
 * @author Ron
 */
public class cashier_portal extends javax.swing.JFrame {

    /**
     * Creates new form cashier_portal
     */
    public cashier_portal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonapple = new javax.swing.JButton();
        jButton2meat = new javax.swing.JButton();
        jButton3orange = new javax.swing.JButton();
        jButton4unga = new javax.swing.JButton();
        jButton5grapes = new javax.swing.JButton();
        jButton6Broccli = new javax.swing.JButton();
        jButton7rice = new javax.swing.JButton();
        jButton8fish = new javax.swing.JButton();
        jButton9carrots = new javax.swing.JButton();
        jButton10beans = new javax.swing.JButton();
        jButton11whisky = new javax.swing.JButton();
        jButton12cucumbers = new javax.swing.JButton();
        jButton13tomatoes = new javax.swing.JButton();
        jButton14soap = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jCheckBoxunga = new javax.swing.JCheckBox();
        jCheckBoxmeat = new javax.swing.JCheckBox();
        jCheckBoxfish = new javax.swing.JCheckBox();
        jCheckBoxrice = new javax.swing.JCheckBox();
        jCheckBoxbeans = new javax.swing.JCheckBox();
        jCheckBoxwhisky = new javax.swing.JCheckBox();
        jCheckBoxsoap = new javax.swing.JCheckBox();
        jCheckBoxorange = new javax.swing.JCheckBox();
        jCheckBoxgrapes = new javax.swing.JCheckBox();
        jCheckBobroccli = new javax.swing.JCheckBox();
        jCheckBoxcucumbers = new javax.swing.JCheckBox();
        jCheckBoxcarrots = new javax.swing.JCheckBox();
        jCheckBoxtomatoes = new javax.swing.JCheckBox();
        jCheckBoxapple = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextapple1 = new javax.swing.JTextField();
        jTextorange = new javax.swing.JTextField();
        jTextgrapes = new javax.swing.JTextField();
        jTextbroccli = new javax.swing.JTextField();
        jTextcucumbers = new javax.swing.JTextField();
        jTextcarrots = new javax.swing.JTextField();
        jTexttomatoes = new javax.swing.JTextField();
        jTextmeat9 = new javax.swing.JTextField();
        jTextunga10 = new javax.swing.JTextField();
        jTextFish11 = new javax.swing.JTextField();
        jTextrice2 = new javax.swing.JTextField();
        jTextbeans3 = new javax.swing.JTextField();
        jTextwhisky14 = new javax.swing.JTextField();
        jTextsoap = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldreciept = new javax.swing.JTextField();
        jTextField16tax = new javax.swing.JTextField();
        jTextField17subtotal = new javax.swing.JTextField();
        jTextField18total = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2147, 2147));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(705, 705));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButtonapple.setText("Apple");
        jButtonapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonappleActionPerformed(evt);
            }
        });

        jButton2meat.setText("Meat");
        jButton2meat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2meatActionPerformed(evt);
            }
        });

        jButton3orange.setText("Orange");
        jButton3orange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3orangeActionPerformed(evt);
            }
        });

        jButton4unga.setText("Unga");
        jButton4unga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ungaActionPerformed(evt);
            }
        });

        jButton5grapes.setText("Grapes");
        jButton5grapes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5grapesActionPerformed(evt);
            }
        });

        jButton6Broccli.setText("Brocclii");
        jButton6Broccli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6BroccliActionPerformed(evt);
            }
        });

        jButton7rice.setText("Rice");
        jButton7rice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7riceActionPerformed(evt);
            }
        });

        jButton8fish.setText("Fish");
        jButton8fish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8fishActionPerformed(evt);
            }
        });

        jButton9carrots.setText("Carrots");
        jButton9carrots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9carrotsActionPerformed(evt);
            }
        });

        jButton10beans.setText("Beans");
        jButton10beans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10beansActionPerformed(evt);
            }
        });

        jButton11whisky.setText("Whisky");
        jButton11whisky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11whiskyActionPerformed(evt);
            }
        });

        jButton12cucumbers.setText("Cucumbers");
        jButton12cucumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12cucumbersActionPerformed(evt);
            }
        });

        jButton13tomatoes.setText("Tomatoes");

        jButton14soap.setText("Soap");
        jButton14soap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14soapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonapple)
                    .addComponent(jButton3orange)
                    .addComponent(jButton5grapes)
                    .addComponent(jButton6Broccli)
                    .addComponent(jButton12cucumbers)
                    .addComponent(jButton9carrots)
                    .addComponent(jButton13tomatoes))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2meat)
                                .addGap(37, 37, 37))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4unga)
                                    .addComponent(jButton8fish)
                                    .addComponent(jButton7rice))
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton14soap)
                            .addComponent(jButton11whisky)
                            .addComponent(jButton10beans))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonapple)
                    .addComponent(jButton2meat))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3orange)
                    .addComponent(jButton4unga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8fish)
                    .addComponent(jButton5grapes))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6Broccli)
                    .addComponent(jButton7rice))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12cucumbers)
                    .addComponent(jButton10beans))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9carrots)
                    .addComponent(jButton11whisky))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14soap)
                    .addComponent(jButton13tomatoes))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel5.setText("Apple");

        jLabel8.setText("Unga");

        jLabel9.setText("Grapes");

        jLabel10.setText("Fish");

        jLabel11.setText("Rice");

        jLabel12.setText("Broccli");

        jLabel13.setText("Beans");

        jLabel14.setText("Cucumbers ");

        jLabel15.setText("Whisky");

        jLabel16.setText("Carrots");

        jLabel18.setText("Tomatoes");

        jLabel19.setText("Soap");

        jCheckBoxunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxungaActionPerformed(evt);
            }
        });

        jCheckBoxmeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxmeatActionPerformed(evt);
            }
        });

        jCheckBoxfish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxfishActionPerformed(evt);
            }
        });

        jCheckBoxrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxriceActionPerformed(evt);
            }
        });

        jCheckBoxbeans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxbeansActionPerformed(evt);
            }
        });

        jCheckBoxwhisky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxwhiskyActionPerformed(evt);
            }
        });

        jCheckBoxsoap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxsoapActionPerformed(evt);
            }
        });

        jCheckBoxorange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxorangeActionPerformed(evt);
            }
        });

        jCheckBoxgrapes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxgrapesActionPerformed(evt);
            }
        });

        jCheckBobroccli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBobroccliActionPerformed(evt);
            }
        });

        jCheckBoxcucumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxcucumbersActionPerformed(evt);
            }
        });

        jCheckBoxcarrots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxcarrotsActionPerformed(evt);
            }
        });

        jCheckBoxtomatoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxtomatoesActionPerformed(evt);
            }
        });

        jCheckBoxapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxappleActionPerformed(evt);
            }
        });

        jLabel21.setText("Orange");

        jLabel6.setText("Meat");

        jTextapple1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextapple1ActionPerformed(evt);
            }
        });

        jTextorange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextorangeActionPerformed(evt);
            }
        });

        jTextgrapes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextgrapesActionPerformed(evt);
            }
        });

        jTextbroccli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextbroccliActionPerformed(evt);
            }
        });

        jTextcucumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextcucumbersActionPerformed(evt);
            }
        });

        jTextcarrots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextcarrotsActionPerformed(evt);
            }
        });

        jTexttomatoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexttomatoesActionPerformed(evt);
            }
        });

        jTextrice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextrice2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCheckBoxorange)
                        .addComponent(jCheckBoxgrapes)
                        .addComponent(jCheckBobroccli)
                        .addComponent(jCheckBoxcucumbers)
                        .addComponent(jCheckBoxapple))
                    .addComponent(jCheckBoxcarrots)
                    .addComponent(jCheckBoxtomatoes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextapple1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextorange))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextbroccli))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextgrapes))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextcucumbers, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTexttomatoes)
                            .addComponent(jTextcarrots))))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBoxsoap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jTextsoap, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBoxwhisky)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextwhisky14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCheckBoxunga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCheckBoxmeat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCheckBoxfish)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFish11)
                            .addComponent(jTextmeat9)
                            .addComponent(jTextunga10)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCheckBoxbeans)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCheckBoxrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextrice2)
                            .addComponent(jTextbeans3))))
                .addGap(112, 112, 112))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxmeat)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jCheckBoxapple)
                        .addComponent(jTextapple1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextmeat9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTextunga10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jCheckBoxorange)
                        .addComponent(jLabel21)
                        .addComponent(jTextorange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBoxunga))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jCheckBoxgrapes)
                            .addComponent(jTextgrapes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jTextFish11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBoxfish))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jCheckBobroccli))
                            .addComponent(jCheckBoxrice))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextrice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextbroccli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jCheckBoxcucumbers)
                            .addComponent(jTextcucumbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBoxcarrots)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextcarrots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxbeans)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(jTextbeans3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxwhisky)
                            .addComponent(jLabel15)
                            .addComponent(jTextwhisky14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxsoap)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jTextsoap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxtomatoes)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTexttomatoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18))))))
        );

        jLabel1.setText("Point of sale ");

        jLabel2.setText("Total andRecipt");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel17.setText("Tax");

        jLabel20.setText("Sub total");

        jLabel22.setText("Total");

        jButton1.setText("Total");

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Close");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField17subtotal)
                            .addComponent(jTextField16tax)
                            .addComponent(jTextField18total)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldreciept)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField16tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField17subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel20))
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextField18total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jTextFieldreciept, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(424, 424, 424))
        );

        jLabel4.setText("Goods available");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(81, 81, 81)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9carrotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9carrotsActionPerformed
        // TODO add your handling code here:
         jCheckBoxcarrots.setEnabled(true);
         
    }//GEN-LAST:event_jButton9carrotsActionPerformed

    private void jButton2meatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2meatActionPerformed
        // TODO add your handling code here;
             jCheckBoxmeat.setEnabled(true);
         
    }//GEN-LAST:event_jButton2meatActionPerformed

    private void jButton10beansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10beansActionPerformed
        // TODO add your handling code here:
          jCheckBoxbeans.setEnabled(true);
     
       
    }//GEN-LAST:event_jButton10beansActionPerformed

    private void jCheckBobroccliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBobroccliActionPerformed
        // TODO add your handling code here:
         jCheckBobroccli.setEnabled(true);
           if(jCheckBobroccli.isSelected())
        {
           jTextbroccli.setEnabled(true);
        }
         else
         {
             jTextbroccli.setEnabled(false);
         }
    }//GEN-LAST:event_jCheckBobroccliActionPerformed

    private void jCheckBoxriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxriceActionPerformed
        // TODO add your handling code here:
         jCheckBoxrice.setEnabled(true);
           if(jCheckBoxrice.isSelected())
        {
           jTextrice2.setEnabled(true);
        }
         else
         {
             jTextrice2.setEnabled(false);
         }
    }//GEN-LAST:event_jCheckBoxriceActionPerformed
    
    private void jCheckBoxfishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxfishActionPerformed
        // TODO add your handling code here:
         jCheckBoxfish.setEnabled(true);
           if(jCheckBoxfish.isSelected())
        {
           jTextFish11.setEnabled(true);
        }
         else
         {
             jTextFish11.setEnabled(false);
         }
    }//GEN-LAST:event_jCheckBoxfishActionPerformed

    private void jCheckBoxmeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxmeatActionPerformed
        // TODO add your handling code here:
         jCheckBoxmeat.setEnabled(true);
            if(jCheckBoxmeat.isSelected())
        {
           jTextmeat9.setEnabled(true);
        }
         else
         {
             jTextmeat9.setEnabled(false);
         }
    }//GEN-LAST:event_jCheckBoxmeatActionPerformed

    private void jButton14soapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14soapActionPerformed
        // TODO add your handling code here:
         jCheckBoxsoap.setEnabled(true);
    }//GEN-LAST:event_jButton14soapActionPerformed

    private void jButton12cucumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12cucumbersActionPerformed
        // TODO add your handling code here:
    jCheckBoxcucumbers.setEnabled(true);
    }//GEN-LAST:event_jButton12cucumbersActionPerformed

    private void jTextrice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextrice2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextrice2ActionPerformed

    private void jButtonappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonappleActionPerformed
        // TODO add your handling code here:
         jCheckBoxapple.setEnabled(true);
    }//GEN-LAST:event_jButtonappleActionPerformed

    private void jTextapple1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextapple1ActionPerformed

    }//GEN-LAST:event_jTextapple1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
          jTextapple1.setText("");
          jTextorange.setText("");
          jTextgrapes.setText("");
          jTextbroccli.setText("");
          jTextcucumbers.setText("");
          jTextcarrots.setText("");
          jTexttomatoes.setText("");
          jTextmeat9.setText("");
          jTextunga10.setText("");
          jTextFish11.setText("");
          jTextrice2.setText("");
          jTextbeans3.setText("");
          jTextapple1.setText("");
          jTextsoap.setText("");
          jTextwhisky14.setText("");
          
           
          
          
          jCheckBoxapple.setSelected(false);
           jCheckBoxorange.setSelected(false);
            jCheckBobroccli.setSelected(false);
             jCheckBoxgrapes.setSelected(false);
              jCheckBoxcucumbers.setSelected(false);
               jCheckBoxcarrots.setSelected(false);
                jCheckBoxtomatoes.setSelected(false);
                 jCheckBoxunga.setSelected(false);
                  jCheckBoxfish.setSelected(false);
                   jCheckBoxrice.setSelected(false);
                    jCheckBoxbeans.setSelected(false);
                     jCheckBoxwhisky.setSelected(false);
                      jCheckBoxsoap.setSelected(false);
                       jCheckBoxmeat.setSelected(false);
                  
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jTextapple1.setEnabled(false);
          jTextorange.setEnabled(false);
          jTextgrapes.setEnabled(false);
          jTextbroccli.setEnabled(false);
          jTextcucumbers.setEnabled(false);
          jTextcarrots.setEnabled(false);
          jTexttomatoes.setEnabled(false);
          jTextmeat9.setEnabled(false);
          jTextunga10.setEnabled(false);
          jTextFish11.setEnabled(false);
          jTextrice2.setEnabled(false);
          jTextbeans3.setEnabled(false);
          jTextapple1.setEnabled(false);
          jTextsoap.setEnabled(false);
          jTextwhisky14.setEnabled(false);
          jTextField16tax.setEnabled(false);
          jTextField17subtotal.setEnabled(false);
           jTextField18total.setEnabled(false);
          jTextFieldreciept.setEnabled(false);
          jCheckBoxapple.setEnabled(false);
           jCheckBoxorange.setEnabled(false);
            jCheckBobroccli.setEnabled(false);
             jCheckBoxgrapes.setEnabled(false);
              jCheckBoxcucumbers.setEnabled(false);
                 jCheckBoxunga.setEnabled(false);
                  jCheckBoxfish.setEnabled(false);
                   jCheckBoxrice.setEnabled(false);
                    jCheckBoxbeans.setEnabled(false);
                     jCheckBoxwhisky.setEnabled(false);
                      jCheckBoxsoap.setEnabled(false);
                       jCheckBoxmeat.setEnabled(false);
                  
          
          
    }//GEN-LAST:event_formWindowActivated

    private void jButton3orangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3orangeActionPerformed
        // TODO add your handling code here:
                 jCheckBoxorange.setEnabled(true);
    }//GEN-LAST:event_jButton3orangeActionPerformed

    private void jButton5grapesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5grapesActionPerformed
        // TODO add your handling code here:
                 jCheckBoxgrapes.setEnabled(true);
    }//GEN-LAST:event_jButton5grapesActionPerformed

    private void jButton6BroccliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6BroccliActionPerformed
        // TODO add your handling code here:
                 jCheckBobroccli.setEnabled(true);
    }//GEN-LAST:event_jButton6BroccliActionPerformed

    private void jButton4ungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ungaActionPerformed
        // TODO add your handling code here:
              jCheckBoxunga.setEnabled(true);
    }//GEN-LAST:event_jButton4ungaActionPerformed

    private void jButton8fishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8fishActionPerformed
        // TODO add your handling code here:
              jCheckBoxfish.setEnabled(true);
    }//GEN-LAST:event_jButton8fishActionPerformed

    private void jButton7riceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7riceActionPerformed
        // TODO add your handling code here:
              jCheckBoxrice.setEnabled(true);
    }//GEN-LAST:event_jButton7riceActionPerformed

    private void jButton11whiskyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11whiskyActionPerformed
        // TODO add your handling code here:
              jCheckBoxwhisky.setEnabled(true);
    }//GEN-LAST:event_jButton11whiskyActionPerformed

    private void jCheckBoxappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxappleActionPerformed
        // TODO add your handling code here:
         if(jCheckBoxapple.isSelected())
        {
           jTextapple1.setEnabled(true);
        }
         else
         {
             jTextapple1.setEnabled(false);
         }
           
    }//GEN-LAST:event_jCheckBoxappleActionPerformed

    private void jTextorangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextorangeActionPerformed
        
           
    }//GEN-LAST:event_jTextorangeActionPerformed

    private void jTextgrapesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextgrapesActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextgrapesActionPerformed

    private void jTextbroccliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextbroccliActionPerformed
        // TODO add your handling code here:
       
           
        
    }//GEN-LAST:event_jTextbroccliActionPerformed

    private void jTextcucumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextcucumbersActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_jTextcucumbersActionPerformed

    private void jTextcarrotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextcarrotsActionPerformed
        // TODO add your handling code here:
       
           
    }//GEN-LAST:event_jTextcarrotsActionPerformed

    private void jTexttomatoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexttomatoesActionPerformed
        // TODO add your handling code here:
       
           
    }//GEN-LAST:event_jTexttomatoesActionPerformed

    private void jCheckBoxorangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxorangeActionPerformed
        // TODO add your handling code here:
          if(jCheckBoxapple.isSelected())
        {
           jTextapple1.setEnabled(true);
        }
         else
         {
             jTextapple1.setEnabled(false);
         }
    }//GEN-LAST:event_jCheckBoxorangeActionPerformed

    private void jCheckBoxgrapesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxgrapesActionPerformed
        // TODO add your handling code here:
          if(jCheckBoxorange.isSelected())
        {
           jTextorange.setEnabled(true);
        }
         else
         {
             jTextorange.setEnabled(false);
         }
    }//GEN-LAST:event_jCheckBoxgrapesActionPerformed

    private void jCheckBoxcucumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxcucumbersActionPerformed
        // TODO add your handling code here:
           if(jCheckBoxcucumbers.isSelected())
        {
           jTextcucumbers.setEnabled(true);
        }
         else
         {
             jTextcucumbers.setEnabled(false);
         }
    }//GEN-LAST:event_jCheckBoxcucumbersActionPerformed

    private void jCheckBoxungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxungaActionPerformed
        // TODO add your handling code here:
           if(jCheckBoxunga.isSelected())
        {
           jTextunga10.setEnabled(true);
        }
         else
         {
             jTextunga10.setEnabled(false);
         }
    }//GEN-LAST:event_jCheckBoxungaActionPerformed

    private void jCheckBoxbeansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxbeansActionPerformed
        // TODO add your handling code here:
           if(jCheckBoxbeans.isSelected())
        {
           jTextbeans3.setEnabled(true);
        }
         else
         {
             jTextbeans3.setEnabled(false);
         }
    }//GEN-LAST:event_jCheckBoxbeansActionPerformed

    private void jCheckBoxwhiskyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxwhiskyActionPerformed
        // TODO add your handling code here:
           if(jCheckBoxwhisky.isSelected())
        {
           jTextwhisky14.setEnabled(true);
        }
         else
         {
             jTextwhisky14.setEnabled(false);
         }
    }//GEN-LAST:event_jCheckBoxwhiskyActionPerformed

    private void jCheckBoxsoapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxsoapActionPerformed
        // TODO add your handling code here:
           if(jCheckBoxbeans.isSelected())
        {
           jTextsoap.setEnabled(true);
        }
         else
         {
             jTextsoap.setEnabled(false);
         }
    }//GEN-LAST:event_jCheckBoxsoapActionPerformed

    private void jCheckBoxtomatoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxtomatoesActionPerformed
        // TODO add your handling code here:
           if(jCheckBoxtomatoes.isSelected())
        {
           jTexttomatoes.setEnabled(true);
        }
         else
         {
             jTexttomatoes.setEnabled(false);
         }
    }//GEN-LAST:event_jCheckBoxtomatoesActionPerformed

    private void jCheckBoxcarrotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxcarrotsActionPerformed
        // TODO add your handling code here:
           if(jCheckBoxcarrots.isSelected())
        {
           jTextcarrots.setEnabled(true);
        }
         else
         {
             jTextcarrots.setEnabled(false);
         }
    }//GEN-LAST:event_jCheckBoxcarrotsActionPerformed

     private void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashier_portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashier_portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashier_portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashier_portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cashier_portal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10beans;
    private javax.swing.JButton jButton11whisky;
    private javax.swing.JButton jButton12cucumbers;
    private javax.swing.JButton jButton13tomatoes;
    private javax.swing.JButton jButton14soap;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton2meat;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton3orange;
    private javax.swing.JButton jButton4unga;
    private javax.swing.JButton jButton5grapes;
    private javax.swing.JButton jButton6Broccli;
    private javax.swing.JButton jButton7rice;
    private javax.swing.JButton jButton8fish;
    private javax.swing.JButton jButton9carrots;
    private javax.swing.JButton jButtonapple;
    private javax.swing.JCheckBox jCheckBobroccli;
    private javax.swing.JCheckBox jCheckBoxapple;
    private javax.swing.JCheckBox jCheckBoxbeans;
    private javax.swing.JCheckBox jCheckBoxcarrots;
    private javax.swing.JCheckBox jCheckBoxcucumbers;
    private javax.swing.JCheckBox jCheckBoxfish;
    private javax.swing.JCheckBox jCheckBoxgrapes;
    private javax.swing.JCheckBox jCheckBoxmeat;
    private javax.swing.JCheckBox jCheckBoxorange;
    private javax.swing.JCheckBox jCheckBoxrice;
    private javax.swing.JCheckBox jCheckBoxsoap;
    private javax.swing.JCheckBox jCheckBoxtomatoes;
    private javax.swing.JCheckBox jCheckBoxunga;
    private javax.swing.JCheckBox jCheckBoxwhisky;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField16tax;
    private javax.swing.JTextField jTextField17subtotal;
    private javax.swing.JTextField jTextField18total;
    private javax.swing.JTextField jTextFieldreciept;
    private javax.swing.JTextField jTextFish11;
    private javax.swing.JTextField jTextapple1;
    private javax.swing.JTextField jTextbeans3;
    private javax.swing.JTextField jTextbroccli;
    private javax.swing.JTextField jTextcarrots;
    private javax.swing.JTextField jTextcucumbers;
    private javax.swing.JTextField jTextgrapes;
    private javax.swing.JTextField jTextmeat9;
    private javax.swing.JTextField jTextorange;
    private javax.swing.JTextField jTextrice2;
    private javax.swing.JTextField jTextsoap;
    private javax.swing.JTextField jTexttomatoes;
    private javax.swing.JTextField jTextunga10;
    private javax.swing.JTextField jTextwhisky14;
    // End of variables declaration//GEN-END:variables
}
